# Generated by Django 3.2.20 on 2023-08-19 21:22

from django.db import migrations, models


def update_user_name_id(apps, schema_editor):
    Comment = apps.get_model('blog', 'Comment')
    User = apps.get_model('auth', 'User')

    for comment in Comment.objects.all():
        user = User.objects.get(username=comment.user_name)
        comment.user_name_id = user.id
        comment.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_user_name'),  
    ]

    operations = [
        migrations.RunPython(update_user_name_id),
    ]
